### ISSUE TITLE
1.1.4 breaks previous config

### ISSUE THREAD

**Issue by KatoNamus** [Caltinor/PMMO-and-NBT-Compat#1]
Hi, first off; thank you for this excellent binding mod (binding all our favourite custom mods into PMMO).

Please note, it seems like 1.1.4 is messing around with previous configs. I'm playing my own custom modpack with the idea of eventually releasing it. I'm currently using a TiC all wooden pickaxe that went from not requiring Mining (just getting the green "Tool" in the tooltip) before updating this mod to requiring Mining 30 (red in the tooltip as I"m currently only on Mining 6.89). I'm using the configs from your examples library and exporting with the slash command shows that the item's details are still the same. 
Emptying out "req_tool_nbt.json" makes the pickaxe require Mining 10, so PMMO-and-NBT-Compat seems to be looking at the configs but also seems to be calculating them a lot differently now.
Downgrading to 1.1.3 and without touching the newly generated "xp_value_*_nbt.json" files seems to resolve my problem but obviously I'd like the benefit of the new features as well, please.

Also, I do have quite a few other mods loaded... total 442 at the moment. Yeah, I'm going for a "SuperPack"
Please advise if I can add any additional information (I forgot to get the logs before restarting after downgrading but am willing to upgrade again to get them for you if you need them).

Thanking you in advance,
Kato

**Comment by Caltinor** [comment]
Kato, thank you for bringing this to my attention. Could you please provide the `re_tool_nbt.json` that was working in 1.1.3 but not 1.1.4? I would like to test this on my end and see what created this breaking change.

**Comment by KatoNamus** [comment]
Thanks for the quick response, Caltinor. Here you go, from my currently active instance. I just tacked the .txt on for GitHub's sake.

[req_tool_nbt.json.txt](https://github.com/Caltinor/PMMO-and-NBT-Compat/files/6489247/req_tool_nbt.json.txt)

**Comment by Caltinor** [comment]
this has been fixed in https://github.com/Caltinor/PMMO-and-NBT-Compat/commit/5c14ee54836102aacabc7f30a6a026a3d5047a86 and is now released on CF as 1.1.4a.  thank you for bringing this to my attention.

**Comment by KatoNamus** [comment]
Thank you (apologies if this comment reopens the issue, if it does and I can, I'll just close it again, otherwise please just close it)
