### ISSUE TITLE
Mod fails to load properly

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [Caltinor/PMMO-and-NBT-Compat#2]
Mod crashes when loading during startup.

Error Message that Not Enough Crashes gives:
PMMO and NBT Compat Mod (dicemcpmmonbt) has failed to load correctly

FML Crash Log
https://pastebin.com/dpF74pnY

latest.log File
https://1drv.ms/u/s!AjMFk0M6vnyIgfBl3ctYh-5kExvvYw?e=lYF28I

**Comment by Caltinor** [comment]
@PliskintheSaltyFork, Thank you for your report.  The log lets me know it is an NPE, but I am unable to reproduce the error to find what is null.  Could you please provide steps to reproduce the error?

**Comment by OnlyAde** [comment]
Had the same issue, it fixed the crash on startup when i updated to the latest forge (36.2.8) and i see you're running 36.2.6 in your log. Maybe updating will help you.

**Comment by Caltinor** [comment]
Found the source of the error. When Harmony added the dim reqs, my code wasn't expecting to have another file to scan for. I am working on a fix now and will have it up and released tomorrow morning.

**Comment by Corwin00420** [comment]
> Found the source of the error. When Harmony added the dim reqs, my code wasn't expecting to have another file to scan for. I am working on a fix now and will have it up and released tomorrow morning.

Any chance you can port this fix to 1.18.2? 
My server is crashing on dicemcpmmonbt-1.18-1.2.1.jar with Project_MMO-1.18.2-3.69.11.jar forge 40.1.68
