### ISSUE TITLE
Request and help

### ISSUE THREAD

**Issue by 78codemonkey** [Caltinor/PMMO-and-NBT-Compat#3]
mc: 1.18.2 : forge 40.1.76 : pmmo and nbt : 1.18-1.2.1

1. is request for iron furnace just like iron chests, place requirement, place xp, and corresponding xp gain when used, (maybe less xp gain on user per furnace tier since they are faster)
2. is request for mana and artifice, magic level requirements on items, blocks and spells, mana bonus with wans, staffs, books, and worn, magic xp gain with work stations used, golem creation, spell creation, and spell/staff use
3. Help: how to adjust current config for tinkers to require correct level requirement (without combat unless weapon) type by material use. example: wood pickaxe head (not bindings or handles) will require only lvl one mining, or stone blade will only require combat 10
wood = lvl 1
stone = lvl 10
gold = lvl 30
diamond = lvl 40/50
netherite = 80

tried adjusting nbt configs in pmmo to true and changing the numbers to example above. but crafting stone pickaxe with wood binding and handle, the pickaxe still requires mining lvl 20-22 and combat 21

**Comment by Caltinor** [comment]
> 1. is request for iron furnace just like iron chests, place requirement, place xp, and corresponding xp gain when used, (maybe less xp gain on user per furnace tier since they are faster)

Not something PMMO can do.  stop asking.

> 2. is request for mana and artifice, magic level requirements on items, blocks and spells, mana bonus with wans, staffs, books, and worn, magic xp gain with work stations used, golem creation, spell creation, and spell/staff use

Not something PMMO can do.  stop asking.

> 3. Help: how to adjust current config for tinkers to require correct level requirement (without combat unless weapon) type by material use. example: wood pickaxe head (not bindings or handles) will require only lvl one mining, or stone blade will only require combat 10
>    wood = lvl 1
>    stone = lvl 10
>    gold = lvl 30
>    diamond = lvl 40/50
>    netherite = 80
> 
> tried adjusting nbt configs in pmmo to true and changing the numbers to example above. but crafting stone pickaxe with wood binding and handle, the pickaxe still requires mining lvl 20-22 and combat 21

You need to change the path in the config from `["tic_materials[]"]` to `["tic_materials[3]"]` since that is the material index of the pickaxe head.  The current setting applies your config to all materials. If you wanted to still have levels attached to bindings and handles, you would add another logic entry with the appropriate path and values that you want.

**Comment by 78codemonkey** [comment]
gonna try it now, I'll have another response after testing it.

**Comment by 78codemonkey** [comment]
it worked for tinkers, just need find frying pan id and rewrite the code for that
any suggestions for adding iron furnace and MNA?

**Comment by Caltinor** [comment]
> any suggestions for adding iron furnace and MNA?

Get those mod authors to add compat.

**Comment by 78codemonkey** [comment]
ok, i'll write a post for them
