### ISSUE TITLE
Weapon Req NBT not working

### ISSUE THREAD

**Issue by WessTheWise** [Caltinor/PMMO-and-NBT-Compat#4]
[req_weapon_nbt.txt](https://github.com/Caltinor/PMMO-and-NBT-Compat/files/9595043/req_weapon_nbt.txt)

So our req_tool_nbt works perfectly fine with tetra but the req_weapon_nbt one is not.

**Comment by Caltinor** [comment]
Then something in the paths is not correct.  if you do `/nbtprint` on the weapon, what do you get?

**Comment by WessTheWise** [comment]
![image](https://user-images.githubusercontent.com/113856734/190927582-94dfad37-41b9-44e9-95d9-dfa9c6ffe003.png)

**Comment by Caltinor** [comment]
that should work.  the sword should have combat 20 as it's level.  The Json is valid.  what version of PMMO are you using?

**Comment by EnderAis** [comment]
Having the same issue. The combat requirements do change, but they're different from what they should be.
[req_weapon_nbt.txt](https://github.com/Caltinor/PMMO-and-NBT-Compat/files/9698175/req_weapon_nbt.txt)
![image](https://user-images.githubusercontent.com/44770535/193598427-61115358-3a70-4cae-9162-902fac763959.png)
Example is this. The scythe has combat 76 requirement for some reason. Do I have to state all the warforged requirements as well?
Everything else from Tetra seems to work fine, only tetra:modular_double is being weird, or me.

**Comment by Caltinor** [comment]
Okay,  I will try and look into this.  I'm hoping it's not a pmmo, bug too, but at least now i'm the maintainer for PMMO so i can fix it if it is.

**Comment by EnderAis** [comment]
A little update on the issue: seems like PMMOs' req_weapon config has the similar issue: config has one req, game has the other.
Config:
![image](https://user-images.githubusercontent.com/44770535/193695537-4c4c7fa6-6dcb-4b3d-a061-1c0e80b51560.png)
In-game:
![image](https://user-images.githubusercontent.com/44770535/193695613-a5cb5fa9-6aa3-46e2-a5cc-927d0369edff.png)

As for the requirements for some of Tetra stuff, found out you can just disable said requirements for modular weapons in PMMO config in game. The other funny thing with this, it only disables the weird stuff  (tetra:modular_double).
Dynamic weapon req enabled:
![image](https://user-images.githubusercontent.com/44770535/193694661-04dbb572-835c-45fd-8eb6-e363594583f3.png)
![image](https://user-images.githubusercontent.com/44770535/193694886-d2113b2f-4f0c-4e75-8179-a0c3281ea95e.png)
Dynamic weapon req disabled:
![image](https://user-images.githubusercontent.com/44770535/193695334-726df657-00fb-4634-a736-f2ec10207c85.png)
![image](https://user-images.githubusercontent.com/44770535/193695360-53561fbf-50dd-48de-aafe-cec995822a22.png)

No idea if this would help but oh well

**Comment by Caltinor** [comment]
Usually a dynamic req replacing a static req is due to a syntax error in the config.  Double check that your req_weapon is a valid json.  If it is, then something is really wrong with weapon reqs and I'm not sure ehow nobody noticed to this point.

**Comment by EnderAis** [comment]
Yeah, my req_weapon was invalid, now non-modular items work fine.

**Comment by Caltinor** [comment]
> Yeah, my req_weapon was invalid, now non-modular items work fine.
Does that mean your NBT settings work too?

**Comment by Caltinor** [comment]
okay, so we have the req_weapon.json working,  that file has no reference to a tetra item, but our nbt req weapon json does, and we are still getting dynamic values unless dynamic values are turned off, in which case we have no req.  is that correct?

**Comment by EnderAis** [comment]
> okay, so we have the req_weapon.json working, that file has no reference to a tetra item, but our nbt req weapon json does, and we are still getting dynamic values unless dynamic values are turned off, in which case we have no req. is that correct?

Well yes but actually no. It only happens to tetra:modular_double items. Whe dynamic values are enabled, they completely ignore whatever req is in the config and use dynamic, while the others (tetra:modular_single, tetra:modular_crossbow, tetra:modular_bow, tetra:modular_sword) DO use config requirements. When dynamic values are disabled though, only tetra:modular_double items actually get affected and no longer have weapon req at all (they still seem to have req of 1, because the "weapon" in their description is not gone), while the others still work fine. 

It looks like the tetra:modular_double isn't in config at all, yet it's there and everything seems good.

**Comment by EnderAis** [comment]
> > Yeah, my req_weapon was invalid, now non-modular items work fine.
> 
> Does that mean your NBT settings work too?

So... I am sorry for the troubles. I re-rechecked everything in the req_weapon_nbt config and rewrote some stuff regarding Tetra from scratch. All works perfectly fine now. Some lessons have also been learned, like actualy using my own brain to fix the issue first.
[req_weapon_nbt.txt](https://github.com/Caltinor/PMMO-and-NBT-Compat/files/9736920/req_weapon_nbt.txt)
Here's the working config. The balancing is made for my own modpack though.
Once again, I'm sincerely sorry for the troubles.

**Comment by Caltinor** [comment]
No worries.  i'm glad it was sorted out.  For my own curiosity, do you know what the issue was?

**Comment by EnderAis** [comment]
> No worries. i'm glad it was sorted out. For my own curiosity, do you know what the issue was?

As it turned out Tetra has some inconsistecies with paths for modular_double items. The main difference is the word "basic". Example: "double/basic_axe_left_material" but "double/hoe_left_material".
Also one of the "double" has way less usable materials (hammers cannot be golden nor diamond).
All it took is just look closely into items' nbts and remove unneeded words and lines.

**Comment by Caltinor** [comment]
That's good to know.  Thank you!
