### ISSUE TITLE
mod failed to load properly

### ISSUE THREAD

**Issue by Tenchu98** [Caltinor/PMMO-and-NBT-Compat#5]
I am getting an error in my pack suddenly, it was working fine until after I uploaded it to curseforge.

**Comment by Tenchu98** [comment]
https://pastebin.com/gqgjdkry

**Comment by Caltinor** [comment]
That's because you are using the alpha version of pmmo, which is a complete rewrite.   That version has NBT compat embedded, so you don't need the extra mod, but it's not feature-complete. 

Roll pmmo back to a release version to fix your issue

**Comment by Tenchu98** [comment]
thank you
