### ISSUE TITLE
unable to load the mod. 

### ISSUE THREAD

**Issue by VirtualGaming1** [Caltinor/PMMO-and-NBT-Compat#7]
MC 1.18.2 Forge: 40.1.76 and Latest. Mod: 1.2.1

![image](https://user-images.githubusercontent.com/20447403/202597565-37579990-d5d5-45d0-9e83-dcc06b100bf4.png)

Nothing in the log

**Comment by VirtualGaming1** [comment]
Update. This is caused by the latest update from Project MMO and it is a re write

**Comment by Caltinor** [comment]
Correct.  pmmo 1.18.2-4.0.0 includes the NBT features of this mod, so this is not necessary anymore.

**Comment by VirtualGaming1** [comment]
that is great to hear. Thanks for letting me know about this
